package com.example.pdfcreation4;

import androidx.appcompat.app.AppCompatActivity;

import android.app.Dialog;
import android.content.res.Resources;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;

import com.gkemon.XMLtoPDF.PdfGenerator;
import com.gkemon.XMLtoPDF.PdfGeneratorListener;
import com.gkemon.XMLtoPDF.model.FailureResponse;
import com.gkemon.XMLtoPDF.model.SuccessResponse;

import java.util.zip.Inflater;

public class MainActivity extends AppCompatActivity {

    Button btGenerate;
    public final int deviceHeight   = Resources.getSystem().getDisplayMetrics().heightPixels;
    public final int deviceWidth    = Resources.getSystem().getDisplayMetrics().widthPixels;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        btGenerate = findViewById(R.id.button);

        btGenerate.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                PdfGenerator.getBuilder()
                        .setContext(MainActivity.this)
                        .fromLayoutXMLSource()
                        .fromLayoutXML(R.layout.pdf_test)
                        .setFileName("Test-PDF")
                        .setFolderNameOrPath("Downloads")
                        .actionAfterPDFGeneration(PdfGenerator.ActionAfterPDFGeneration.OPEN)
                        .build(new PdfGeneratorListener() {
                            @Override
                            public void onFailure(FailureResponse failureResponse) {
                                super.onFailure(failureResponse);
                                /* If pdf is not generated by an error then you will findout the reason behind it
                                 * from this FailureResponse. */
                            }
                            @Override
                            public void onStartPDFGeneration() {
                                /*When PDF generation begins to start*/
                            }

                            @Override
                            public void onFinishPDFGeneration() {
                                /*When PDF generation is finished*/
                            }

                            @Override
                            public void showLog(String log) {
                                super.showLog(log);
                                /*It shows logs of events inside the pdf generation process*/
                            }

                            @Override
                            public void onSuccess(SuccessResponse response) {
                                super.onSuccess(response);
                                /* If PDF is generated successfully then you will find SuccessResponse
                                 * which holds the PdfDocument,File and path (where generated pdf is stored)*/

                            }
                        });

            }
        });
    }
}